python scripts/parse_history.py reports/TRIAL3_1/history/ loss TRIAL3_1 -ptbr
python scripts/parse_history.py reports/TRIAL3_2/history/ loss TRIAL3_2 -ptbr
python scripts/parse_history.py reports/TRIAL3_3/history/ loss TRIAL3_3 -ptbr
python scripts/parse_history.py reports/TRIAL3_4/history/ loss TRIAL3_4 -ptbr
python scripts/parse_history.py reports/TRIAL3_1/history/ val_loss TRIAL3_1 -ptbr
python scripts/parse_history.py reports/TRIAL3_2/history/ val_loss TRIAL3_2 -ptbr
python scripts/parse_history.py reports/TRIAL3_3/history/ val_loss TRIAL3_3 -ptbr
python scripts/parse_history.py reports/TRIAL3_4/history/ val_loss TRIAL3_4 -ptbr
python scripts/parse_history.py reports/TRIAL3_1/history/ val_R_squared TRIAL3_1 -ptbr
python scripts/parse_history.py reports/TRIAL3_2/history/ val_R_squared TRIAL3_2 -ptbr
python scripts/parse_history.py reports/TRIAL3_3/history/ val_R_squared TRIAL3_3 -ptbr
python scripts/parse_history.py reports/TRIAL3_4/history/ val_R_squared TRIAL3_4 -ptbr
python scripts/parse_history.py reports/TRIAL3_1/history/ val_mse TRIAL3_1 -ptbr
python scripts/parse_history.py reports/TRIAL3_2/history/ val_mse TRIAL3_2 -ptbr
python scripts/parse_history.py reports/TRIAL3_3/history/ val_mse TRIAL3_3 -ptbr
python scripts/parse_history.py reports/TRIAL3_4/history/ val_mse TRIAL3_4 -ptbr
